name: envi_metrix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  equatable: ^2.0.5
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  rive: ^0.12.4
  mapbox_gl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
