name: envi_metrix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  equatable: ^2.0.5
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  fl_chart: ^0.66.1
  intl: ^0.19.0
  flutter_gemini: ^2.0.3
  floating_draggable_widget: ^2.1.5
  flutter_markdown: ^0.6.19
  flutter_svg: ^2.0.10+1
  gauge_indicator: ^0.4.3
  share_plus: ^7.2.2
  facebook_messenger_share: ^0.0.3
  fluttertoast: ^8.2.4
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/data/
